### ISSUE TITLE
InfluxDB backup/restore npm module

### ISSUE THREAD

**Issue by robertsLando** [danesparza/influxdb-ui#11]
Hi, I have just published `influx-backup`, an npm module that allows to backup/restore influxdb databases. Any feedback is welcome. 
Check it here --> https://www.npmjs.com/package/influx-backup

**Comment by danesparza** [comment]
Looks like sources are here: https://github.com/robertsLando/node-influxdb-backup -- is that right?

**Comment by robertsLando** [comment]
Yes, right :)
