### ISSUE TITLE
Installing on local apache only returns empty page

### ISSUE THREAD

**Issue by DutchmanNL** [danesparza/influxdb-ui#2]
Hi,

Thank you providing the interface !
I tried to install it on my local apache installation, the index page is reachable but only returns an empty page.

influxdB, apache server and your admin are installed on the same host, i see the title InfluxDB UI but nothing is shown:

![screen shot 2018-04-24 at 15 16 33](https://user-images.githubusercontent.com/7318445/39189432-86f75c1c-47d2-11e8-8b53-3137b10b815a.png)

debug output of safari:

![screen shot 2018-04-24 at 15 19 00](https://user-images.githubusercontent.com/7318445/39189589-dc4df496-47d2-11e8-89e7-b86be3f97cd5.png)
![screen shot 2018-04-24 at 15 19 05](https://user-images.githubusercontent.com/7318445/39189592-e02b0630-47d2-11e8-8b9c-68d16c92e889.png)

**Comment by DutchmanNL** [comment]
was able to fix the issue by hosting the page directly in the web root directory, how can i change this to an subdirectory path ?

**Comment by danesparza** [comment]
Doh!  Good catch, @DutchmanNL -- I just needed to make [this change to package.json](https://github.com/danesparza/influxdb-ui/blob/master/package.json#L3) -- give it a shot now with the latest release.
