### ISSUE TITLE
Does not allow using port 80 and assumes the default 8086

### ISSUE THREAD

**Issue by yapily-joao** [danesparza/influxdb-ui#3]
My InfluxDB is using a different port than the 8086 and the UI does not accept any other port.
When providing a specific port, the record becomes :8086 automatically.

**Comment by danesparza** [comment]
Hmmm ... I suspect it's related to [this line](https://github.com/danesparza/influxdb-ui/blob/8b28aa1cfd37a014bce831b0bd33417313ed42b8/src/components/Settings.js#L118).  I'll need to sort out why it's not getting set correctly.  Thanks for the heads up!

**Comment by yapily-joao** [comment]
Ah, it only doesn't work with the port :80
The other ports work fine.
The URL parser, even if the 80 is provided, automatically considers it as empty, then the condition that you pointed out uses the default 8086.
I will change the title of the issue to mention the port 80 only.

**Comment by danesparza** [comment]
What browser are you using?  In Chrome 67 (on my machine) this works just fine

**Comment by danesparza** [comment]
I can repro with port 80.  Thanks for that piece of info!  Trying to figure out what the issue is...

**Comment by yapily-joao** [comment]
When you [set the href of the parser](https://github.com/danesparza/influxdb-ui/blob/8b28aa1cfd37a014bce831b0bd33417313ed42b8/src/components/Settings.js#L116), if it is port 80, the port becomes empty.
I'm using chrome 67.

**Comment by danesparza** [comment]
Fixed and smoke tested.  I would say a build should be up soon -- but CircleCI (the automated build engine for this project) [appears to be down](https://status.circleci.com/).  😢
