### ISSUE TITLE
influxdb with authentication

### ISSUE THREAD

**Issue by Meissnerim** [danesparza/influxdb-ui#4]
Your projects looks really nice. Is there a way to use it if my influxdb is configured to use credentials?
I tried to add my credentials to the url but it looks like they get cut.

https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/

**Comment by danesparza** [comment]
Excellent question.  Right now, the app only supports instances without authentication ... although [looking at the docs](https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/#authentication), it might be easy to add.
